version: '3.7'
services:
  web:
    restart: always
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
#    volumes:
#      - ./persist_data:/home/app/persist_data
    ports:
      - 8000:8000
  redis:
    restart: always
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A task worker -l info
    volumes:
      - .:/home/app
    depends_on:
      - redis
      - web
  celery_beat:
    restart: always
    build:
      context: .
    command: celery -A task beat
#    volumes:
#      - ./persist_data:/home/app/persist_data
    depends_on:
      - redis
      - web

